### ISSUE TITLE
Setting CN_AGENT_SIZE > 0.5 causes segfault

### ISSUE THREAD

**Issue by ctbend** [PathPlanning/Continuous-CBS#2]
Using the following map/task: [Examples.zip](https://github.com/PathPlanning/Continuous-CBS/files/5075053/Examples.zip) setting CN_AGENT_SIZE > 0.5 causes a segmentation fault with all other settings at default. Some debugging shows this starts with Map::check_line - within Map::get_grid.

Is CN_AGENT_SIZE > 0.5 meant to be supported?

**Comment by aandreychuk** [comment]
Nope, only sizes in range (0; 0.5] are supported. At least for now.

**Comment by ctbend** [comment]
Ok, thanks for the quick response. Perhaps this could be updated in the documentation.
