### ISSUE TITLE
Which tool can be used to show the search result like animations in DEMO？

### ISSUE THREAD

**Issue by mz-smt** [PathPlanning/Continuous-CBS#4]
Which tool can be used to show the search result like animations in DEMO？

**Comment by robintomar1** [comment]
not sure about animation but you can definately use matplotlib to plot the paths of agents in x,y,t dimentions. 
![Figure_2](https://user-images.githubusercontent.com/34551411/131834902-f55e517d-9859-460e-9c27-f02fb74f3beb.png)
 something like this.
