### ISSUE TITLE
function check_conflict may exist error

### ISSUE THREAD

**Issue by mz-smt** [PathPlanning/Continuous-CBS#5]
Parameters m1i1 m1i2 ...in function check_conflict shall be changed to double?

**Comment by aandreychuk** [comment]
Right. In case of roadmaps i,j coordinates can be double.
Thanks for notice. I've merged your your pull request.

**Comment by mz-smt** [comment]
> 
Thanks for reply.
I have another question. I find in grid map case, if the length of one edge in the map is shorter than the radius dimension of two cars, the algorithm may fail. 

> Right. In case of roadmaps i,j coordinates can be double. Thanks for notice. I've merged your your pull request.
